name: CI/CD pipeline for Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST}} >> ~/.ssh/known_hosts
          echo "SSH Successfull"

      - name: Deploy to Azure VM
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.APP_DIR }}

            # Pull latest changes
            git reset --hard
            git pull origin master

            # Remove old containers and images
            docker compose down
            docker system prune -af

            # Restart containers
            docker compose up -d
          EOF